const LEVELS={1:{tag:'LOADS OF HELP',face:'👶'},2:{tag:'NORMAL HELP',face:'🙂'},3:{tag:'TRICKY',face:'😩'},4:{tag:'SNEAKY',face:'😈'}};
const CUSTOM_META={name:'Our own words',emoji:'✏️'};
const EXAMPLE_WORDS=`Grandma's dog | A pet somebody in this room knows
Our caravan | Somewhere this family has stayed
Dad's snoring | A noise you hear at home
The school run | Something that happens every morning
Nana's roast potatoes | Food somebody here is famous for`;
const state={playerCount:5,names:[],levels:[],points:[],imposterCount:1,pack:'random',customText:'',clueRounds:2,voteMode:'secret',readAloud:true,timerSeconds:120,sound:true,scores:{crew:0,imp:0},gamesPlayed:0,roles:[],secret:null,shortlist:[],revealIndex:0,revealLevel:2,helpUsed:[],order:[],roundNo:1,voterIndex:0,ballots:[],picks:[],accused:[],used:new Set(),resolved:false};
const $=id=>document.getElementById(id),screens=[...document.querySelectorAll('.screen')];
function show(id){screens.forEach(s=>s.classList.toggle('is-active',s.id===id));if(id==='s-home')$('scoreBtn').classList.toggle('hidden',state.gamesPlayed===0);if(id!=='s-reveal')stopSpeech();window.scrollTo({top:0,behavior:'auto'})}
function defaultName(i){return `Player ${i+1}`};function playerName(i){return(state.names[i]||'').trim()||defaultName(i)}
function shuffle(a){a=a.slice();for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function beep(freq,ms){if(!state.sound)return;try{const C=window.AudioContext||window.webkitAudioContext;if(!C)return;const c=new C(),o=c.createOscillator(),g=c.createGain();o.type='square';o.frequency.value=freq;g.gain.setValueAtTime(.06,c.currentTime);g.gain.exponentialRampToValueAtTime(.001,c.currentTime+ms/1000);o.connect(g);g.connect(c.destination);o.start();o.stop(c.currentTime+ms/1000);setTimeout(()=>c.close(),ms+120)}catch{}}
const canSpeak='speechSynthesis'in window;function speak(t){if(!canSpeak)return;try{speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-GB';u.rate=.85;u.pitch=1.05;speechSynthesis.speak(u)}catch{}}function stopSpeech(){if(canSpeak)try{speechSynthesis.cancel()}catch{}}
function parseCustom(t){return t.split('\n').map(x=>x.trim()).filter(Boolean).map(x=>{const p=x.split('|');return[p[0].trim(),(p[1]||'').trim()||'Something from your own word pack']}).filter(x=>x[0])}
function packWords(k){return k==='custom'?parseCustom(state.customText):PACKS[k].words}function packMeta(k){return k==='custom'?CUSTOM_META:{name:PACKS[k].name,emoji:PACKS[k].emoji}}
function ensureArrays(){for(let i=0;i<state.playerCount;i++){if(state.levels[i]==null)state.levels[i]=2;if(state.points[i]==null)state.points[i]=0}}
function renderPlayerRows(){ensureArrays();const box=$('playerRows');box.innerHTML='';for(let i=0;i<state.playerCount;i++){const row=document.createElement('div');row.className='prow';const inp=document.createElement('input');inp.type='text';inp.maxLength=12;inp.placeholder=defaultName(i);inp.value=state.names[i]||'';inp.setAttribute('aria-label',`Name for player ${i+1}`);inp.oninput=e=>state.names[i]=e.target.value;row.appendChild(inp);const set=document.createElement('div');set.className='lvlset';[1,2,3,4].forEach(lv=>{const b=document.createElement('button');b.className='lvl'+(state.levels[i]===lv?' on':'');b.dataset.level=lv;b.textContent=LEVELS[lv].face;b.setAttribute('aria-label',`${playerName(i)}: ${LEVELS[lv].tag}`);b.onclick=()=>{state.levels[i]=lv;renderPlayerRows();beep(560,50)};set.appendChild(b)});row.appendChild(set);box.appendChild(row)}}
function setImposters(n){state.imposterCount=n;document.querySelectorAll('#impPills .pill').forEach(p=>p.classList.toggle('on',Number(p.dataset.imp)===n))}
function updatePlayerCount(d){state.playerCount=Math.min(10,Math.max(3,state.playerCount+d));$('playerCount').textContent=state.playerCount;const ok=state.playerCount>=6,two=document.querySelector('[data-imp="2"]');two.disabled=!ok;if(!ok&&state.imposterCount===2)setImposters(1);$('impNote').textContent=ok?"Two imposters makes it much trickier — they don't know who each other is!":'Two imposters needs 6 or more players.';renderPlayerRows()}
$('minusPlayers').onclick=()=>{updatePlayerCount(-1);beep(400,60)};$('plusPlayers').onclick=()=>{updatePlayerCount(1);beep(600,60)};document.querySelectorAll('#impPills .pill').forEach(p=>p.onclick=()=>setImposters(Number(p.dataset.imp)));document.querySelectorAll('#setAll .lvl').forEach(b=>b.onclick=()=>{const lv=Number(b.dataset.level);for(let i=0;i<state.playerCount;i++)state.levels[i]=lv;renderPlayerRows();beep(620,70)});
function renderPacks(){const box=$('catPills');box.innerHTML='';const all=document.createElement('button');all.className='pill on';all.dataset.pack='random';all.textContent='🎲 A bit of everything';box.appendChild(all);Object.entries(PACKS).forEach(([k,p])=>{const b=document.createElement('button');b.className='pill';b.dataset.pack=k;b.textContent=`${p.emoji} ${p.name}`;box.appendChild(b)});const own=document.createElement('button');own.className='pill hidden';own.dataset.pack='custom';own.id='customPill';own.textContent='✏️ Our own words';box.appendChild(own);box.onclick=e=>{const b=e.target.closest('.pill');if(!b)return;state.pack=b.dataset.pack;box.querySelectorAll('.pill').forEach(p=>p.classList.toggle('on',p===b))}}
function pickPack(k){state.pack=k;document.querySelectorAll('#catPills .pill').forEach(p=>p.classList.toggle('on',p.dataset.pack===k))}
document.querySelectorAll('#roundPills .pill').forEach(p=>p.onclick=()=>{state.clueRounds=Number(p.dataset.rounds);document.querySelectorAll('#roundPills .pill').forEach(x=>x.classList.toggle('on',x===p))});
function renderVoteNote(){$('voteNote').textContent=state.voteMode==='secret'?'The phone goes round again and everyone votes on their own. Nobody can copy the loudest player.':'Quicker: count down from three, everybody points, then tap the player who got pointed at most.'}
document.querySelectorAll('#votePills .pill').forEach(p=>p.onclick=()=>{state.voteMode=p.dataset.vote;document.querySelectorAll('#votePills .pill').forEach(x=>x.classList.toggle('on',x===p));renderVoteNote()});document.querySelectorAll('#timePills .pill').forEach(p=>p.onclick=()=>{state.timerSeconds=Number(p.dataset.time);document.querySelectorAll('#timePills .pill').forEach(x=>x.classList.toggle('on',x===p))});document.querySelectorAll('#readPills .pill').forEach(p=>p.onclick=()=>{state.readAloud=p.dataset.read==='1';document.querySelectorAll('#readPills .pill').forEach(x=>x.classList.toggle('on',x===p))});
function renderCustomCount(){const n=parseCustom($('customText').value).length;$('customCount').textContent=`${n} ${n===1?'word':'words'} ready${n<3?' — you need at least 3':' ✔'}`;$('customSave').disabled=n<3}
$('customBtn').onclick=()=>{$('customText').value=state.customText;renderCustomCount();show('s-custom')};$('customText').oninput=renderCustomCount;$('customExample').onclick=()=>{$('customText').value=EXAMPLE_WORDS;renderCustomCount()};$('customClear').onclick=()=>{$('customText').value='';renderCustomCount()};$('customBack').onclick=()=>show('s-home');$('customSave').onclick=()=>{state.customText=$('customText').value;$('customPill').classList.remove('hidden');pickPack('custom');show('s-home')};
function pickSecret(){let pool=[];if(state.pack==='random')Object.entries(PACKS).forEach(([k,p])=>p.words.forEach(w=>pool.push({word:w[0],clue:w[1],cat:p.name,emoji:p.emoji,key:k})));else{const m=packMeta(state.pack);packWords(state.pack).forEach(w=>pool.push({word:w[0],clue:w[1],cat:m.name,emoji:m.emoji,key:state.pack}))}let fresh=pool.filter(w=>!state.used.has(w.word));if(!fresh.length){state.used.clear();fresh=pool}const c=fresh[Math.floor(Math.random()*fresh.length)];state.used.add(c.word);return c}
function startRound(){ensureArrays();state.secret=pickSecret();state.roles=new Array(state.playerCount).fill('crew');shuffle([...Array(state.playerCount).keys()]).slice(0,state.imposterCount).forEach(i=>state.roles[i]='imposter');state.order=shuffle([...Array(state.playerCount).keys()]);state.revealIndex=0;state.roundNo=1;state.picks=[];state.accused=[];state.ballots=[];state.helpUsed=[];state.resolved=false;const others=packWords(state.secret.key).map(w=>w[0]).filter(w=>w!==state.secret.word);state.shortlist=shuffle([state.secret.word,...shuffle(others).slice(0,2)]);showReveal()}
function impostors(){return state.roles.map((r,i)=>r==='imposter'?i:-1).filter(i=>i>-1)}function wordSize(w){return w.length<=9?'xl':w.length<=15?'lg':'md'}
function showReveal(){const i=state.revealIndex;state.revealLevel=state.levels[i];$('passName').textContent=playerName(i);$('pack').classList.remove('is-open','imposter');$('nextPlayerBtn').classList.add('hidden');$('roleBody').innerHTML='';show('s-reveal')}
function cardButtons(help){let h='<div class="cardbtns">';if(state.readAloud&&canSpeak)h+='<button class="cardbtn" id="readBtn">🔊 READ IT TO ME</button>';if(help)h+='<button class="cardbtn" id="helpBtn">🙋 I NEED A BIGGER CLUE</button>';return h+'</div>'}
function renderCard(){const s=state.secret,lv=state.revealLevel,b=$('roleBody'),isImp=state.roles[state.revealIndex]==='imposter';if(!isImp){b.innerHTML=`<div class="the-word ${wordSize(s.word)}">${s.word}</div><span class="cat-tag">${s.emoji} ${s.cat.toUpperCase()}</span><p class="tip">Say one word that goes with this — but don't make it too easy for the imposter.</p>${cardButtons(false)}`;return}const clue=`<div class="clue-box"><p class="eyebrow">YOUR CLUE</p><div class="clue">${s.clue}</div></div>`,tag=`<span class="cat-tag">${s.emoji} ${s.cat.toUpperCase()}</span>`;let h=`<span class="level-badge">${LEVELS[lv].face} ${LEVELS[lv].tag}</span>`;if(lv===4)h+=`<div class="clue-box"><p class="eyebrow">ALL YOU GET</p><div class="clue">${s.emoji} ${s.cat}</div></div><p class="tip">No clue, and no asking for help. Let someone else go first, then bluff like mad.</p>`;else if(lv===3)h+=clue+`<p class="tip">That's your lot — you don't even get the pack name. Listen hard.</p>`;else if(lv===2)h+=clue+tag+`<p class="tip">Everyone else knows the real word. Say something that fits your clue and blend in.</p>`;else h+=clue+tag+`<div class="shortlist"><p class="eyebrow">IT'S ONE OF THESE THREE</p><div class="chips">${state.shortlist.map(w=>`<span class="mini">${w}</span>`).join('')}</div></div><p class="tip">Say something that would fit all three and nobody will know which one you mean.</p>`;b.innerHTML=h+cardButtons(lv>1&&lv<4)}
function cardSpeech(){const s=state.secret,lv=state.revealLevel;if(state.roles[state.revealIndex]!=='imposter')return`Your secret word is. ${s.word}`;if(lv===4)return`You are the imposter. All you get is the pack. ${s.cat}`;if(lv===1)return`You are the imposter. Your clue is. ${s.clue}. It is one of these three. ${state.shortlist.join('. ')}`;return`You are the imposter. Your clue is. ${s.clue}`}
function openPack(){const p=$('pack');if(p.classList.contains('is-open'))return;const imp=state.roles[state.revealIndex]==='imposter';$('roleLabel').textContent=imp?"🕵️ YOU'RE THE IMPOSTER":'YOUR SECRET WORD';p.classList.toggle('imposter',imp);renderCard();beep(imp?220:660,imp?180:140);p.classList.add('is-open');setTimeout(()=>$('nextPlayerBtn').classList.remove('hidden'),450)}
$('packFront').onclick=openPack;$('packFront').onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();openPack()}};$('roleBody').onclick=e=>{if(e.target.closest('#readBtn'))return speak(cardSpeech());if(e.target.closest('#helpBtn')&&state.revealLevel>1&&state.revealLevel<4){state.revealLevel--;if(!state.helpUsed.includes(state.revealIndex))state.helpUsed.push(state.revealIndex);renderCard();beep(520,120)}};$('nextPlayerBtn').onclick=()=>{stopSpeech();state.revealIndex++;state.revealIndex>=state.playerCount?showPlay():showReveal()};
let timerId=null,remaining=0,running=false;function fmt(s){return`${Math.floor(s/60)}:${String(s%60).padStart(2,'0')}`}function paintClock(){$('clock').textContent=fmt(remaining);$('clock').classList.toggle('warn',remaining<=30&&remaining>0)}function stopTimer(){clearInterval(timerId);timerId=null;running=false;$('timerStart').textContent='▶ START'}function toggleTimer(){if(running)return stopTimer();running=true;$('timerStart').textContent='⏸ PAUSE';timerId=setInterval(()=>{remaining--;paintClock();if(remaining<=0){stopTimer();$('clock').textContent='TIME!';beep(880,200);setTimeout(()=>beep(660,300),240)}},1000)}
$('timerStart').onclick=toggleTimer;$('timerReset').onclick=()=>{stopTimer();remaining=state.timerSeconds;paintClock()};
function showPlay(){const rot=(state.roundNo-1)%state.playerCount,order=state.order.slice(rot).concat(state.order.slice(0,rot));$('roundPill').textContent=`CLUE ROUND ${state.roundNo} OF ${state.clueRounds}`;const list=$('orderList');list.innerHTML='';order.forEach((p,i)=>{const li=document.createElement('li');if(!i)li.classList.add('first');li.innerHTML=`<span class="num">${i+1}</span><span>${playerName(p)}</span>${!i?'<span class="starts">STARTS 👈</span>':''}`;list.appendChild(li)});stopTimer();if(state.timerSeconds===0)$('timerPanel').classList.add('hidden');else{$('timerPanel').classList.remove('hidden');remaining=state.timerSeconds;paintClock()}$('nextPhaseBtn').textContent=state.roundNo<state.clueRounds?'➡️ NEXT CLUE ROUND':'🗳️ TIME TO VOTE';show('s-play')}
$('nextPhaseBtn').onclick=()=>{stopTimer();if(state.roundNo<state.clueRounds){state.roundNo++;showPlay()}else state.voteMode==='secret'?startBallots():showQuickVote()};
function showQuickVote(){const g=$('voteGrid');g.innerHTML='';state.picks=[];$('voteHint').textContent=state.imposterCount===1?'Count down from three and everyone point at once. Then tap that player.':'There are two imposters. Tap the two players who got pointed at most.';for(let i=0;i<state.playerCount;i++){const b=document.createElement('button');b.className='vote-btn';b.textContent=playerName(i);b.onclick=()=>{const at=state.picks.indexOf(i);if(at>-1)state.picks.splice(at,1);else if(state.picks.length<state.imposterCount)state.picks.push(i);g.querySelectorAll('.vote-btn').forEach((x,j)=>x.classList.toggle('picked',state.picks.includes(j)));$('revealBtn').disabled=state.picks.length!==state.imposterCount};g.appendChild(b)}$('revealBtn').disabled=true;show('s-vote')}$('revealBtn').onclick=()=>{state.accused=state.picks.slice();showResult()};
function startBallots(){state.ballots=new Array(state.playerCount).fill(null);state.voterIndex=0;showBallot()}function showBallot(){const v=state.voterIndex;$('ballotName').textContent=playerName(v);$('ballotAsk').classList.remove('hidden');$('ballotGrid').classList.remove('hidden');$('ballotLock').classList.add('hidden');$('ballotNext').classList.add('hidden');const g=$('ballotGrid');g.innerHTML='';for(let i=0;i<state.playerCount;i++){const b=document.createElement('button');b.className='vote-btn';b.textContent=playerName(i);if(i===v){b.disabled=true;b.textContent=`${playerName(i)} (you)`}b.onclick=()=>{state.ballots[v]=i;$('ballotAsk').classList.add('hidden');g.classList.add('hidden');$('ballotLock').classList.remove('hidden');$('ballotNext').classList.remove('hidden');beep(540,90)};g.appendChild(b)}show('s-ballot')}
$('ballotNext').onclick=()=>{state.voterIndex++;state.voterIndex>=state.playerCount?countBallots():showBallot()};function voteCounts(){const c=new Array(state.playerCount).fill(0);state.ballots.forEach(v=>{if(v!=null)c[v]++});return c}function renderTally(el){const c=voteCounts(),max=Math.max(1,...c);el.innerHTML=c.map((n,i)=>`<div class="tallyrow"><span class="nm">${playerName(i)}</span><span class="bar"><span style="width:${Math.round(n/max*100)}%"></span></span><span class="ct">${n}</span></div>`).join('')}function countBallots(){const c=voteCounts(),r=c.map((n,i)=>({i,c:n})).sort((a,b)=>b.c-a.c),n=state.imposterCount,tied=r.length>n&&r[n-1].c===r[n].c;if(tied){renderTally($('tieTally'));show('s-tie');return}state.accused=r.slice(0,n).map(x=>x.i);showResult()}$('tieAgain').onclick=startBallots;$('tieNobody').onclick=()=>{state.accused=[];showResult()};
function paintScores(){$('scoreCrew').textContent=state.scores.crew;$('scoreImp').textContent=state.scores.imp}function renderBoard(el){const rows=[];for(let i=0;i<state.playerCount;i++)rows.push({i,p:state.points[i]||0});rows.sort((a,b)=>b.p-a.p);const m=['🥇','🥈','🥉'];el.innerHTML=rows.map((r,i)=>`<div class="boardrow${i===0&&r.p>0?' lead':''}"><span class="pos">${i<3&&r.p>0?m[i]:`${i+1}.`}</span><span>${playerName(r.i)}</span><span class="pts">${r.p}</span></div>`).join('')}$('scoreBtn').onclick=()=>{renderBoard($('boardPanel'));show('s-scores')};$('scoresBack').onclick=()=>show('s-home');$('resetScoreBtn').onclick=()=>{state.scores={crew:0,imp:0};state.points=new Array(state.playerCount).fill(0);state.gamesPlayed=0;paintScores();renderBoard($('boardPanel'))};
function showResult(){const imps=impostors(),caught=imps.length&&imps.every(i=>state.accused.includes(i));$('rWord').textContent=state.secret.word;$('rImp').textContent=imps.map(playerName).join(' & ');$('rVote').textContent=state.accused.length?state.accused.map(playerName).join(' & '):'Nobody';$('rHelpRow').classList.toggle('hidden',!state.helpUsed.length);if(state.helpUsed.length)$('rHelp').textContent='🙋 '+state.helpUsed.map(playerName).join(' & ');if(state.voteMode==='secret'&&state.ballots.length){renderTally($('resultTally'));$('tallyPanel').classList.remove('hidden')}else $('tallyPanel').classList.add('hidden');if(state.voteMode==='secret')state.ballots.forEach((v,i)=>{if(v!=null&&imps.includes(v))state.points[i]++});else if(caught)for(let i=0;i<state.playerCount;i++)if(!imps.includes(i))state.points[i]++;if(!caught)imps.forEach(i=>state.points[i]+=2);const b=$('resultBanner');$('guessPanel').classList.add('hidden');$('resultActions').classList.add('hidden');$('resultBoard').classList.add('hidden');state.gamesPlayed++;if(caught){b.className='banner win';b.textContent='🔍 CAUGHT THEM!';$('guessPrompt').textContent=imps.length===1?'One last chance, imposter — say what you think the secret word was. Were you right?':'One last chance, imposters — between you, say what the secret word was. Right or wrong?';$('guessPanel').classList.remove('hidden');beep(660,120);setTimeout(()=>beep(880,200),150)}else{b.className='banner lose';b.textContent=state.accused.length?'🕵️ THE IMPOSTER GOT AWAY!':'🕵️ NOBODY WAS CAUGHT!';state.scores.imp++;finishResult();beep(200,300)}show('s-result')}
function finishResult(){state.resolved=true;paintScores();renderBoard($('boardRows'));$('resultBoard').classList.remove('hidden');$('resultActions').classList.remove('hidden')}$('guessYes').onclick=()=>{if(state.resolved)return;$('resultBanner').className='banner lose';$('resultBanner').textContent='😱 CAUGHT — BUT THEY GUESSED IT!';state.scores.imp++;impostors().forEach(i=>state.points[i]++);$('guessPanel').classList.add('hidden');finishResult()};$('guessNo').onclick=()=>{if(state.resolved)return;$('resultBanner').className='banner win';$('resultBanner').textContent='🏆 DETECTIVES WIN!';state.scores.crew++;$('guessPanel').classList.add('hidden');finishResult()};$('nextRoundBtn').onclick=startRound;$('newGameBtn').onclick=()=>{stopTimer();show('s-home')};
$('startBtn').onclick=()=>{if(state.pack==='custom'&&parseCustom(state.customText).length<3)pickPack('random');startRound()};$('rulesBtn').onclick=()=>show('s-rules');$('rulesBack').onclick=()=>show('s-home');$('soundBtn').onclick=()=>{state.sound=!state.sound;$('soundBtn').textContent=state.sound?'🔊':'🔇';$('soundBtn').setAttribute('aria-label',state.sound?'Turn sound off':'Turn sound on');if(state.sound)beep(700,90)};
renderPacks();renderVoteNote();updatePlayerCount(0);paintScores();if(!canSpeak)document.querySelectorAll('#readPills .pill').forEach(p=>p.disabled=true);
